//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tinyCleaner.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tinyCleaner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check all.
        /// </summary>
        public static string CheckAllBoxes {
            get {
                return ResourceManager.GetString("CheckAllBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check updates on start.
        /// </summary>
        public static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clean browser cache.
        /// </summary>
        public static string CleanBrowserCache {
            get {
                return ResourceManager.GetString("CleanBrowserCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clean NVIDIA and Microsoft Office Cache.
        /// </summary>
        public static string CleanNVMOCache {
            get {
                return ResourceManager.GetString("CleanNVMOCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clean.
        /// </summary>
        public static string CleanTabText {
            get {
                return ResourceManager.GetString("CleanTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clean Temp folders.
        /// </summary>
        public static string CleanTemp {
            get {
                return ResourceManager.GetString("CleanTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clean Windows Update cache.
        /// </summary>
        public static string CleanUpdateCache {
            get {
                return ResourceManager.GetString("CleanUpdateCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clean WinSxS.
        /// </summary>
        public static string CleanWSxS {
            get {
                return ResourceManager.GetString("CleanWSxS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable auto updates.
        /// </summary>
        public static string DisableAutoUpdates {
            get {
                return ResourceManager.GetString("DisableAutoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable Cortana.
        /// </summary>
        public static string DisableCortana {
            get {
                return ResourceManager.GetString("DisableCortana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable Xbox DVR.
        /// </summary>
        public static string DisableDVR {
            get {
                return ResourceManager.GetString("DisableDVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable error reporting.
        /// </summary>
        public static string DisableErrorReport {
            get {
                return ResourceManager.GetString("DisableErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable telemetry and other unnecessary services.
        /// </summary>
        public static string DisableServices {
            get {
                return ResourceManager.GetString("DisableServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable everything in Privacy Settings.
        /// </summary>
        public static string DisableSettingsPrivacy {
            get {
                return ResourceManager.GetString("DisableSettingsPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable Sync.
        /// </summary>
        public static string DisableSync {
            get {
                return ResourceManager.GetString("DisableSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove Windows Defender.
        /// </summary>
        public static string DisableWindowsDefender {
            get {
                return ResourceManager.GetString("DisableWindowsDefender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable Windows Tips.
        /// </summary>
        public static string DisableWindowsTips {
            get {
                return ResourceManager.GetString("DisableWindowsTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty Recycle Bin.
        /// </summary>
        public static string EmptyRecycleBin {
            get {
                return ResourceManager.GetString("EmptyRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open GitHub Repo.
        /// </summary>
        public static string OpenGH {
            get {
                return ResourceManager.GetString("OpenGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove Paint 3D from context menu.
        /// </summary>
        public static string RemovePaint3D {
            get {
                return ResourceManager.GetString("RemovePaint3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uncheck all.
        /// </summary>
        public static string UnCheckAllBoxes {
            get {
                return ResourceManager.GetString("UnCheckAllBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update Now.
        /// </summary>
        public static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By using this program, you agree to the following license..
        /// </summary>
        public static string UseLicense {
            get {
                return ResourceManager.GetString("UseLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UWP Apps.
        /// </summary>
        public static string UWOAppsTabText {
            get {
                return ResourceManager.GetString("UWOAppsTabText", resourceCulture);
            }
        }
    }
}
